{
  # Import all your configuration modules here
  imports = [
    ./auto-save.nix
    ./barbecue.nix
    ./better-escape.nix
    ./bufferline.nix
    ./chadtree.nix
    ./cmp.nix
    ./dashboard.nix
    ./direnv.nix
    ./edgy.nix
    ./fidget.nix
    ./fugitive.nix
    ./gitgutter.nix
    ./harpoon.nix
    ./helm.nix
    ./illuminate.nix
    ./leap.nix
    ./lint.nix
    ./lsp.nix
    ./luasnip.nix
    ./neoclip.nix
    ./nvim-autopairs.nix
    ./nvim-bqf.nix
    ./nvim-surround.nix
    ./nvim-ufo.nix
    ./obsidian.nix
    ./ollama.nix
    ./precognition.nix
    ./sleuth.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./trouble.nix
    ./undotree.nix
    ./which-key.nix
    ./wilder.nix
  ];
}
